#!/usr/bin/env bun
/**
 * Builds the signage assets the plugin ships.
 *
 * Output lands in screenly-cast/assets/dist and is COMMITTED, because
 * WordPress.org runs no build step — the plugin has to carry its own compiled
 * CSS and JS. CI re-runs this and fails if the committed output differs, which is
 * the only thing standing between a stale asset and a silent regression.
 */

import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { GATE, bundleJs, processCss } from '@screenly-labs/signage-kit/build'
import { syncFonts } from '@screenly-labs/signage-kit/sync-fonts'
import { $ } from 'bun'

const DIST = 'screenly-cast/assets/dist'
const CSS_ENTRY = 'src/css/signage.css'
const JS_ENTRY = 'src/js/signage.ts'

/**
 * Only the families the design actually uses. @font-face is lazy, but vendoring
 * unused files would still bloat the plugin zip.
 */
const FONT_FAMILIES = ['bricolage-grotesque', 'hanken-grotesk', 'space-mono']

const CSS_OUT = `${DIST}/signage.css`
const JS_OUT = `${DIST}/signage.js`
const GATE_OUT = `${DIST}/gate.php`

/**
 * Wrap the degraded-mode gate as a PHP file.
 *
 * A PHP file rather than raw HTML so the template can `require` it: that keeps it
 * clear of the output-escaping rules a read-and-echo would trip, and lets opcache
 * hold it.
 */
function gatePhp(): string {
  return `<?php
/**
 * The degraded-mode gate.
 *
 * GENERATED by build.ts from @screenly-labs/signage-kit — do not edit. Run
 * \`bun run build\` to regenerate.
 *
 * Marks the document html.legacy when the engine renders below the support floor
 * or the hardware looks weak, so the stylesheet can drop animation.
 *
 * @package ScreenlyCast
 */

defined( 'ABSPATH' ) || exit;
?>
${GATE}
`
}

async function main(): Promise<void> {
  await rm(DIST, { recursive: true, force: true })
  await mkdir(`${DIST}/fonts`, { recursive: true })

  // Tailwind resolves the @import graph (its own layers, plus the signage-kit
  // preset), then the shared pipeline down-levels the result to the support floor.
  console.log('› Tailwind')
  await $`bunx @tailwindcss/cli --input ${CSS_ENTRY} --output ${CSS_OUT}`.quiet()

  console.log('› Down-levelling CSS to the support floor')
  const compiled = await readFile(CSS_OUT, 'utf8')
  const processed = await processCss(compiled, { flattenLayers: true, filename: CSS_OUT })
  await writeFile(CSS_OUT, processed)

  console.log('› Bundling JS')
  await bundleJs(JS_ENTRY, JS_OUT)

  console.log('› Degraded-mode gate')
  await writeFile(GATE_OUT, gatePhp())

  console.log('› Fonts')
  await syncFonts(FONT_FAMILIES, `${DIST}/fonts`)

  console.log(`\nBuilt into ${DIST}`)
}

await main()
