#!/usr/bin/env bun
/**
 * Seeds the fixture corpus into the wp-env site.
 *
 * Idempotent: anything seeded by a previous run is deleted first, so the corpus
 * and the manifest the spec reads always agree.
 *
 * Content is written to files and handed to wp-cli by path rather than passed as
 * a command-line argument — the fixtures contain quotes, angle brackets and
 * multi-byte text, none of which survive shell quoting reliably.
 */

import { mkdir, rm, writeFile } from 'node:fs/promises'
import { $ } from 'bun'
import { FIXTURES } from './fixtures'
import { makeSampleImage } from './make-sample-image'

const ARTIFACTS = 'tests/e2e/.artifacts'
const CONTENT_DIR = `${ARTIFACTS}/content`
const MANIFEST = `${ARTIFACTS}/fixtures.json`

/** Path to the repo root as mounted inside the wp-env containers. */
const CONTAINER_ROOT = '/var/www/html/srly'

/**
 * The sample photograph, generated by make-sample-image.ts.
 *
 * Deliberately a bright, high-key image: the scrim has to keep a headline legible
 * over the worst realistic case, not the flattering one.
 */
const SAMPLE_IMAGE = `${CONTAINER_ROOT}/tests/e2e/.artifacts/sample-photo.png`

export type SeededFixture = {
  key: string
  id: number
  url: string
}

/**
 * Run a wp-cli command in the wp-env cli container and return its clean output.
 *
 * wp-env decorates the output with progress lines, which have to be stripped
 * before a `--porcelain` value can be read.
 */
async function wp(args: string[]): Promise<string> {
  const result = await $`bunx wp-env run cli wp ${args}`.quiet()
  const text = result.stdout.toString()

  return text
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line !== '')
    .filter((line) => !/^[ℹ✔✖⚠]/.test(line))
    .filter((line) => !line.startsWith('Starting') && !line.startsWith('Ran '))
    .join('\n')
    .trim()
}

/** Evaluate PHP in the site and return the result, for values wp-cli has no field for. */
async function wpEval(php: string): Promise<string> {
  return wp(['eval', php])
}

async function deletePreviouslySeeded(): Promise<void> {
  const file = Bun.file(MANIFEST)
  if (!(await file.exists())) {
    return
  }

  const previous = (await file.json()) as SeededFixture[]
  const ids = previous.map((fixture) => String(fixture.id)).filter((id) => id !== '0')

  if (ids.length === 0) {
    return
  }

  console.log(`› Removing ${ids.length} fixture(s) from the previous run`)
  // Failure here is not fatal: the posts may already be gone.
  await $`bunx wp-env run cli wp post delete ${ids} --force`.quiet().nothrow()
}

async function seed(): Promise<void> {
  await mkdir(CONTENT_DIR, { recursive: true })

  // The sample photograph is generated, not committed, so make it if absent —
  // otherwise a clean checkout (or CI) has nothing to import.
  await makeSampleImage()

  await deletePreviouslySeeded()

  const seeded: SeededFixture[] = []

  for (const fixture of FIXTURES) {
    const contentPath = `${CONTENT_DIR}/${fixture.key}.html`
    await writeFile(contentPath, fixture.content)
    const containerContentPath = `${CONTAINER_ROOT}/${contentPath}`

    let id: number
    let url: string

    if (fixture.type === 'attachment') {
      // The attachment's own page is the render under test.
      const imported = await wp([
        'media',
        'import',
        SAMPLE_IMAGE,
        `--title=${fixture.title}`,
        `--caption=${fixture.content.replace(/<[^>]+>/g, '')}`,
        '--porcelain'
      ])
      id = Number.parseInt(imported, 10)
      url = await wpEval(`echo get_permalink(${id});`)
    } else {
      const created = await wp([
        'post',
        'create',
        containerContentPath,
        `--post_title=${fixture.title}`,
        `--post_type=${fixture.type}`,
        '--post_status=publish',
        '--porcelain'
      ])
      id = Number.parseInt(created, 10)

      if (fixture.featured) {
        const attachmentId = await wp([
          'media',
          'import',
          SAMPLE_IMAGE,
          `--post_id=${id}`,
          '--featured_image',
          '--porcelain'
        ])
        if (!/^\d+$/.test(attachmentId)) {
          throw new Error(`Could not attach a featured image to "${fixture.key}": ${attachmentId}`)
        }
      }

      url = await wpEval(`echo get_permalink(${id});`)
    }

    if (!Number.isInteger(id) || id <= 0) {
      throw new Error(`Failed to seed "${fixture.key}" — wp-cli returned no id`)
    }
    if (!url.startsWith('http')) {
      throw new Error(`Failed to resolve a permalink for "${fixture.key}": ${url}`)
    }

    seeded.push({ key: fixture.key, id, url })
    console.log(`✓ ${fixture.key} (#${id})`)
  }

  // A brand logo, so the corner chrome is exercised too — including the RTL check,
  // which asserts the logo swaps sides via the stylesheet's logical properties.
  const logoId = await wp([
    'media',
    'import',
    `${CONTAINER_ROOT}/.wordpress-org/icon-256x256.png`,
    '--title=Fixture logo',
    '--porcelain'
  ])
  if (/^\d+$/.test(logoId)) {
    await wp(['option', 'update', 'screenly_cast_logo_id', logoId])
    console.log(`✓ logo (#${logoId})`)
  }

  await writeFile(MANIFEST, `${JSON.stringify(seeded, null, 2)}\n`)
  console.log(`\nSeeded ${seeded.length} fixtures into ${MANIFEST}`)
}

// Renders from a previous run would otherwise mislead the contact sheet.
await rm(`${ARTIFACTS}/renders`, { recursive: true, force: true })
await seed()
